# nolint start: object_usage_linter
test_that("independent live regeneration matches the golden canonical payload", {
  # A freshly serialized object cannot be compared byte-for-byte with a
  # checked-in .rds across platforms, and it never could: raw doubles differ by
  # one or two ULP between macOS and Linux, which is the whole reason the hash
  # rounds to nine significant digits. Comparing regenerated bytes made this
  # test assert the opposite of the contract it exists to protect (D-060).
  #
  # The portable comparison is canonical_hash. The checked-in file's own
  # SHA-256 is still verified, in test-golden-fixtures-step8-1.R, where the
  # file is read rather than rebuilt.
  manifest_path <- golden_extdata_path("golden-fixture-manifest.csv")
  manifest <- read.csv(manifest_path, stringsAsFactors = FALSE)
  live_objects <- c(golden_live_jebs_specs(), golden_live_preset_specs())

  for (file in names(live_objects)) {
    row <- manifest[manifest$fixture_file == file, , drop = FALSE]
    expect_identical(nrow(row), 1L)
    expect_identical(
      canonical_hash(live_objects[[file]]),
      row$canonical_hash[[1L]],
      info = file
    )
  }

  readme_source <- test_path("_snaps/golden/README.md")
  readme_copy <- tempfile(pattern = "multisiteDGP-golden-readme-", fileext = ".md")
  writeLines(readLines(readme_source, warn = FALSE), readme_copy, useBytes = TRUE)
  expect_snapshot_file(readme_copy, name = "README.md")
})
# nolint end
